apiVersion: v1
kind: Service
metadata:
 name: spring-petclinic-docker-build-ingress
 namespace: spring-petclinic-docker-build
spec:
 type: LoadBalancer
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
  app: spring-petclinic-docker-build
 loadBalancerIP: 10.0.10.253
